In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [33]:
## Define the vocabulary size
voc_size = 10000


In [47]:
## One hot representation 
one_hot_repr = [one_hot(words, voc_size) for words in sent]
## to tell at which index is the specific word located
one_hot_repr


[[3744, 7027, 2295, 3123],
 [3744, 7027, 2295, 5237],
 [3744, 9507, 2295, 3978],
 [6594, 7994, 2341, 3093, 568],
 [6594, 7994, 2341, 3093, 8233],
 [1359, 3744, 1378, 2295, 2626],
 [878, 8831, 217, 3093]]

In [48]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
##from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [49]:
import numpy as np

In [50]:
## total number of words a sentence can have in a list
sent_length=8
## tells the one hot repr to to add the additional entries before the actual words in a sentence if needed to set it to 8 words for each sentence
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 3744, 7027, 2295, 3123],
       [   0,    0,    0,    0, 3744, 7027, 2295, 5237],
       [   0,    0,    0,    0, 3744, 9507, 2295, 3978],
       [   0,    0,    0, 6594, 7994, 2341, 3093,  568],
       [   0,    0,    0, 6594, 7994, 2341, 3093, 8233],
       [   0,    0,    0, 1359, 3744, 1378, 2295, 2626],
       [   0,    0,    0,    0,  878, 8831,  217, 3093]])

In [51]:
## feature representation
dim = 10


In [52]:
model=Sequential()
## Embedding have integrated Word2Vec and memorize this syntax
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

In [56]:
# Build the model explicitly by providing an input shape(because if this is not done then the summary will show empty dataset)
model.build(input_shape=(None, sent_length))

In [60]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[[ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [-2.35685706e-02, -3.18024382e-02, -4.66481596e-03,
         -3.23299989e-02, -2.37776767e-02, -4.16143909e-02,
         -3.20027620e-02, -7.42421299e-03, -7.757209

In [61]:
embedded_docs[0]

array([   0,    0,    0,    0, 3744, 7027, 2295, 3123])

In [66]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[[ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [ 1.18065998e-03, -1.86969750e-02, -1.55930743e-02,
         -2.36489624e-03, -4.23742905e-02, -4.01561037e-02,
         -2.60852221e-02, -4.55527790e-02, -4.84694168e-03,
          2.90017016e-02],
        [-2.35685706e-02, -3.18024382e-02, -4.66481596e-03,
         -3.23299989e-02, -2.37776767e-02, -4.16143909e-02,
         -3.20027620e-02, -7.42421299e-03, -7.757209